config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :pilotos
  resources :provas
  resources :tracados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/historico_piloto.rb
class HistoricoPiloto < ApplicationRecord
  belongs_to :piloto
  belongs_to :prova
end

app/models/piloto.rb
class Piloto < ApplicationRecord
end

app/models/prova.rb
class Prova < ApplicationRecord
  belongs_to :tracado
end

app/models/tracado.rb
class Tracado < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pilotos_controller.rb
class PilotosController < ApplicationController
  before_action :set_piloto, only: [:show, :edit, :update, :destroy]

  # GET /pilotos
  # GET /pilotos.json
  def index
    @pilotos = Piloto.all
  end

  # GET /pilotos/1
  # GET /pilotos/1.json
  def show
  end

  # GET /pilotos/new
  def new
    @piloto = Piloto.new
  end

  # GET /pilotos/1/edit
  def edit
  end

  # POST /pilotos
  # POST /pilotos.json
  def create
    @piloto = Piloto.new(piloto_params)

    respond_to do |format|
      if @piloto.save
        format.html { redirect_to @piloto, notice: 'Piloto was successfully created.' }
        format.json { render :show, status: :created, location: @piloto }
      else
        format.html { render :new }
        format.json { render json: @piloto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilotos/1
  # PATCH/PUT /pilotos/1.json
  def update
    respond_to do |format|
      if @piloto.update(piloto_params)
        format.html { redirect_to @piloto, notice: 'Piloto was successfully updated.' }
        format.json { render :show, status: :ok, location: @piloto }
      else
        format.html { render :edit }
        format.json { render json: @piloto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilotos/1
  # DELETE /pilotos/1.json
  def destroy
    @piloto.destroy
    respond_to do |format|
      format.html { redirect_to pilotos_url, notice: 'Piloto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piloto
      @piloto = Piloto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piloto_params
      params.require(:piloto).permit(:nome, :cpf, :nascimento, :apelido, :email, :celular)
    end
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  before_action :set_prova, only: [:show, :edit, :update, :destroy]

  # GET /provas
  # GET /provas.json
  def index
    @provas = Prova.all
  end

  # GET /provas/1
  # GET /provas/1.json
  def show
  end

  # GET /provas/new
  def new
    @prova = Prova.new
  end

  # GET /provas/1/edit
  def edit
  end

  # POST /provas
  # POST /provas.json
  def create
    @prova = Prova.new(prova_params)

    respond_to do |format|
      if @prova.save
        format.html { redirect_to @prova, notice: 'Prova was successfully created.' }
        format.json { render :show, status: :created, location: @prova }
      else
        format.html { render :new }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provas/1
  # PATCH/PUT /provas/1.json
  def update
    respond_to do |format|
      if @prova.update(prova_params)
        format.html { redirect_to @prova, notice: 'Prova was successfully updated.' }
        format.json { render :show, status: :ok, location: @prova }
      else
        format.html { render :edit }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provas/1
  # DELETE /provas/1.json
  def destroy
    @prova.destroy
    respond_to do |format|
      format.html { redirect_to provas_url, notice: 'Prova was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prova
      @prova = Prova.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prova_params
      params.require(:prova).permit(:nome, :dia, :horario, :resultado, :tracado_id)
    end
end

app/controllers/tracados_controller.rb
class TracadosController < ApplicationController
  before_action :set_tracado, only: [:show, :edit, :update, :destroy]

  # GET /tracados
  # GET /tracados.json
  def index
    @tracados = Tracado.all
  end

  # GET /tracados/1
  # GET /tracados/1.json
  def show
  end

  # GET /tracados/new
  def new
    @tracado = Tracado.new
  end

  # GET /tracados/1/edit
  def edit
  end

  # POST /tracados
  # POST /tracados.json
  def create
    @tracado = Tracado.new(tracado_params)

    respond_to do |format|
      if @tracado.save
        format.html { redirect_to @tracado, notice: 'Tracado was successfully created.' }
        format.json { render :show, status: :created, location: @tracado }
      else
        format.html { render :new }
        format.json { render json: @tracado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracados/1
  # PATCH/PUT /tracados/1.json
  def update
    respond_to do |format|
      if @tracado.update(tracado_params)
        format.html { redirect_to @tracado, notice: 'Tracado was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracado }
      else
        format.html { render :edit }
        format.json { render json: @tracado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracados/1
  # DELETE /tracados/1.json
  def destroy
    @tracado.destroy
    respond_to do |format|
      format.html { redirect_to tracados_url, notice: 'Tracado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracado
      @tracado = Tracado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracado_params
      params.require(:tracado).permit(:nome, :pista, :imagem, :melhor_tempo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pilotos_helper.rb
module PilotosHelper
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/helpers/tracados_helper.rb
module TracadosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Races</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pilotos/_form.html.erb
<%= form_with(model: piloto, local: true) do |form| %>
  <% if piloto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piloto.errors.count, "error") %> prohibited this piloto from being saved:</h2>

      <ul>
      <% piloto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :nascimento %>
    <%= form.date_select :nascimento %>
  </div>

  <div class="field">
    <%= form.label :apelido %>
    <%= form.text_field :apelido %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pilotos/edit.html.erb
<h1>Editing Piloto</h1>

<%= render 'form', piloto: @piloto %>

<%= link_to 'Show', @piloto %> |
<%= link_to 'Back', pilotos_path %>

app/views/pilotos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pilotos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Nascimento</th>
      <th>Apelido</th>
      <th>Email</th>
      <th>Celular</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pilotos.each do |piloto| %>
      <tr>
        <td><%= piloto.nome %></td>
        <td><%= piloto.cpf %></td>
        <td><%= piloto.nascimento %></td>
        <td><%= piloto.apelido %></td>
        <td><%= piloto.email %></td>
        <td><%= piloto.celular %></td>
        <td><%= link_to 'Show', piloto %></td>
        <td><%= link_to 'Edit', edit_piloto_path(piloto) %></td>
        <td><%= link_to 'Destroy', piloto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piloto', new_piloto_path %>

app/views/pilotos/new.html.erb
<h1>New Piloto</h1>

<%= render 'form', piloto: @piloto %>

<%= link_to 'Back', pilotos_path %>

app/views/pilotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @piloto.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @piloto.cpf %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @piloto.nascimento %>
</p>

<p>
  <strong>Apelido:</strong>
  <%= @piloto.apelido %>
</p>

<p>
  <strong>Email:</strong>
  <%= @piloto.email %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @piloto.celular %>
</p>

<%= link_to 'Edit', edit_piloto_path(@piloto) %> |
<%= link_to 'Back', pilotos_path %>

app/views/provas/_form.html.erb
<%= form_with(model: prova, local: true) do |form| %>
  <% if prova.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prova.errors.count, "error") %> prohibited this prova from being saved:</h2>

      <ul>
      <% prova.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :dia %>
    <%= form.date_select :dia %>
  </div>

  <div class="field">
    <%= form.label :horario %>
    <%= form.text_field :horario %>
  </div>

  <div class="field">
    <%= form.label :resultado %>
    <%= form.text_field :resultado %>
  </div>

  <div class="field">
    <%= form.label :tracado_id %>
    <%= form.text_field :tracado_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provas/edit.html.erb
<h1>Editing Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Show', @prova %> |
<%= link_to 'Back', provas_path %>

app/views/provas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Dia</th>
      <th>Horario</th>
      <th>Resultado</th>
      <th>Tracado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provas.each do |prova| %>
      <tr>
        <td><%= prova.nome %></td>
        <td><%= prova.dia %></td>
        <td><%= prova.horario %></td>
        <td><%= prova.resultado %></td>
        <td><%= prova.tracado %></td>
        <td><%= link_to 'Show', prova %></td>
        <td><%= link_to 'Edit', edit_prova_path(prova) %></td>
        <td><%= link_to 'Destroy', prova, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prova', new_prova_path %>

app/views/provas/new.html.erb
<h1>New Prova</h1>

<%= render 'form', prova: @prova %>

<%= link_to 'Back', provas_path %>

app/views/provas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @prova.nome %>
</p>

<p>
  <strong>Dia:</strong>
  <%= @prova.dia %>
</p>

<p>
  <strong>Horario:</strong>
  <%= @prova.horario %>
</p>

<p>
  <strong>Resultado:</strong>
  <%= @prova.resultado %>
</p>

<p>
  <strong>Tracado:</strong>
  <%= @prova.tracado %>
</p>

<%= link_to 'Edit', edit_prova_path(@prova) %> |
<%= link_to 'Back', provas_path %>

app/views/tracados/_form.html.erb
<%= form_with(model: tracado, local: true) do |form| %>
  <% if tracado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracado.errors.count, "error") %> prohibited this tracado from being saved:</h2>

      <ul>
      <% tracado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :pista %>
    <%= form.text_field :pista %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.text_field :imagem %>
  </div>

  <div class="field">
    <%= form.label :melhor_tempo %>
    <%= form.text_field :melhor_tempo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tracados/edit.html.erb
<h1>Editing Tracado</h1>

<%= render 'form', tracado: @tracado %>

<%= link_to 'Show', @tracado %> |
<%= link_to 'Back', tracados_path %>

app/views/tracados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracados</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Pista</th>
      <th>Imagem</th>
      <th>Melhor tempo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracados.each do |tracado| %>
      <tr>
        <td><%= tracado.nome %></td>
        <td><%= tracado.pista %></td>
        <td><%= tracado.imagem %></td>
        <td><%= tracado.melhor_tempo %></td>
        <td><%= link_to 'Show', tracado %></td>
        <td><%= link_to 'Edit', edit_tracado_path(tracado) %></td>
        <td><%= link_to 'Destroy', tracado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tracado', new_tracado_path %>

app/views/tracados/new.html.erb
<h1>New Tracado</h1>

<%= render 'form', tracado: @tracado %>

<%= link_to 'Back', tracados_path %>

app/views/tracados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @tracado.nome %>
</p>

<p>
  <strong>Pista:</strong>
  <%= @tracado.pista %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= @tracado.imagem %>
</p>

<p>
  <strong>Melhor tempo:</strong>
  <%= @tracado.melhor_tempo %>
</p>

<%= link_to 'Edit', edit_tracado_path(@tracado) %> |
<%= link_to 'Back', tracados_path %>